#!/usr/bin/env node
/**
 * VERA algorithm map
 *
 * Finds every `VERA-ALGO[ID] BEGIN ... VERA-ALGO[ID] END` block in the codebase,
 * checks it against the registry table in docs/ALGORITHM.md, and generates:
 *   docs/ALGORITHM_INDEX.md  – where each algorithm step lives (file + line range)
 *   docs/ALGORITHM_CODE.md   – (--snippets) the code of every block, in pipeline order,
 *                              for printing as a code-review handout
 *
 * Usage (from the repo root):
 *   node scripts/algo-map.mjs             -> write ALGORITHM_INDEX.md
 *   node scripts/algo-map.mjs --snippets  -> also write ALGORITHM_CODE.md
 *   node scripts/algo-map.mjs --check     -> validate only; exit 1 on problems (use in CI / before commit)
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SCAN_DIRS = ["apps", "packages", "supabase"];
const SKIP_DIRS = new Set([
  "node_modules", ".venv", "venv", "dist", "build", "__pycache__", ".turbo",
  ".pytest_cache", "training", "model", "coverage",
]);
const EXTENSIONS = new Map([
  [".py", "python"], [".js", "javascript"], [".mjs", "javascript"], [".jsx", "jsx"],
  [".ts", "typescript"], [".tsx", "tsx"], [".sql", "sql"],
]);
const REGISTRY_FILE = path.join(ROOT, "docs", "ALGORITHM.md");
const INDEX_FILE = path.join(ROOT, "docs", "ALGORITHM_INDEX.md");
const CODE_FILE = path.join(ROOT, "docs", "ALGORITHM_CODE.md");

const MARKER = /VERA-ALGO\[([A-Z]+-\d{2})\]\s+(BEGIN|END)\b\s*(.*)$/;
const REGISTRY_ROW = /^\|\s*`([A-Z]+-\d{2})`\s*\|\s*([^|]+?)\s*\|\s*(implemented|partial|planned)\s*\|/;

const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");
const withSnippets = args.has("--snippets");

function walk(dir, files = []) {
  if (!existsSync(dir)) return files;
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const full = path.join(dir, name);
    const stats = statSync(full);
    if (stats.isDirectory()) walk(full, files);
    else if (EXTENSIONS.has(path.extname(name))) files.push(full);
  }
  return files;
}

function readRegistry() {
  if (!existsSync(REGISTRY_FILE)) {
    throw new Error(`Registry not found: ${path.relative(ROOT, REGISTRY_FILE)}`);
  }
  const rows = [];
  for (const line of readFileSync(REGISTRY_FILE, "utf8").split(/\r?\n/)) {
    const m = line.match(REGISTRY_ROW);
    if (m) rows.push({ id: m[1], step: m[2].trim(), status: m[3] });
  }
  return rows;
}

function scanBlocks(files, problems) {
  const blocks = [];
  for (const file of files) {
    const rel = path.relative(ROOT, file).split(path.sep).join("/");
    const lines = readFileSync(file, "utf8").split(/\r?\n/);
    const open = new Map(); // id -> { start, title }
    lines.forEach((line, i) => {
      const m = line.match(MARKER);
      if (!m) return;
      const [, id, kind, rest] = m;
      const lineNo = i + 1;
      if (kind === "BEGIN") {
        if (open.has(id)) problems.push(`${rel}:${lineNo} nested or repeated BEGIN for ${id}`);
        open.set(id, { start: lineNo, title: rest.trim() });
      } else {
        const begin = open.get(id);
        if (!begin) {
          problems.push(`${rel}:${lineNo} END for ${id} without BEGIN`);
          return;
        }
        open.delete(id);
        blocks.push({
          id,
          title: begin.title,
          file: rel,
          start: begin.start,
          end: lineNo,
          lang: EXTENSIONS.get(path.extname(file)),
          code: lines.slice(begin.start - 1, lineNo).join("\n"),
        });
      }
    });
    for (const [id, begin] of open) problems.push(`${rel}:${begin.start} BEGIN for ${id} has no END`);
  }
  return blocks;
}

function validate(registry, blocks, problems, notes) {
  const known = new Map(registry.map((r) => [r.id, r]));
  const seen = new Set(registry.map((r) => r.id));
  if (seen.size !== registry.length) problems.push("Duplicate IDs in the docs/ALGORITHM.md registry table");

  for (const b of blocks) {
    if (!known.has(b.id)) problems.push(`${b.file}:${b.start} ${b.id} is not in the registry (docs/ALGORITHM.md)`);
  }
  for (const r of registry) {
    const has = blocks.some((b) => b.id === r.id);
    if (!has && r.status !== "planned") problems.push(`${r.id} (${r.status}) has no VERA-ALGO block in the code`);
    if (has && r.status === "planned") notes.push(`${r.id} has code but is still "planned" in the registry; update its status`);
  }
}

function renderIndex(registry, blocks) {
  const out = [
    "# VERA — Algorithm Index (generated)",
    "",
    "> Generated by `pnpm algo:map` from `VERA-ALGO` markers. Do not edit by hand.",
    `> Generated: ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`,
    "> Explanation of every step: [ALGORITHM.md](./ALGORITHM.md)",
    "",
    "| ID | Step | Status | Code location(s) |",
    "|---|---|---|---|",
  ];
  for (const r of registry) {
    const locs = blocks
      .filter((b) => b.id === r.id)
      .map((b) => `[\`${b.file}:${b.start}-${b.end}\`](../${b.file}#L${b.start}-L${b.end})`)
      .join("<br>");
    out.push(`| \`${r.id}\` | ${r.step} | ${r.status} | ${locs || "—"} |`);
  }
  out.push("");
  return out.join("\n");
}

function renderCode(registry, blocks) {
  const out = [
    "# VERA — Algorithm Code Handout (generated)",
    "",
    "> Every `VERA-ALGO` block in pipeline order, for code review. Generated by `pnpm algo:snippets`.",
    `> Generated: ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`,
    "",
  ];
  for (const r of registry) {
    const own = blocks.filter((b) => b.id === r.id);
    if (!own.length) continue;
    out.push(`## ${r.id} — ${r.step}`, "");
    for (const b of own) {
      out.push(`**${b.title || r.step}** · \`${b.file}\` lines ${b.start}–${b.end}`, "");
      out.push("```" + b.lang, b.code, "```", "");
    }
  }
  return out.join("\n");
}

const problems = [];
const notes = [];
const registry = readRegistry();
const blocks = scanBlocks(SCAN_DIRS.flatMap((d) => walk(path.join(ROOT, d))), problems);
validate(registry, blocks, problems, notes);

for (const n of notes) console.log(`note: ${n}`);
if (problems.length) {
  console.error(`\nVERA-ALGO check failed (${problems.length}):`);
  for (const p of problems) console.error(`  - ${p}`);
} else {
  console.log(`VERA-ALGO check passed: ${blocks.length} block(s), ${registry.length} registered step(s).`);
}

if (!checkOnly) {
  writeFileSync(INDEX_FILE, renderIndex(registry, blocks));
  console.log(`wrote ${path.relative(ROOT, INDEX_FILE)}`);
  if (withSnippets) {
    writeFileSync(CODE_FILE, renderCode(registry, blocks));
    console.log(`wrote ${path.relative(ROOT, CODE_FILE)}`);
  }
}

process.exit(problems.length ? 1 : 0);
